### PR TITLE
Clean up the landing page to make the user feel welcome

### PR DESCRIPTION
**Pull request by Catherinesjkim**
### Locations:
- List.js
- package.json
- SearchForm.js
- RenderPinnedCity.js
- ProfileListContainer.js
- RenderUserDashboard.js
- CityOperations.js

### Details:
1) Updated all lines with 'items' to 'cities' and 'data' on RenderPinnedCity.js and RenderUserDashboard.js because we are dealing with 'cities' and 'data', not 'items'.
2) Took out the spread operator state from line 20 in the cityoperations.js file
3) Took out the BroowserRouter import from the App.js file

## Commited Features
1 | Updated text font type and color to make the landing page to look more modern and similar to PM's spec.

### CODE REVIEW

**Review by vetorobert3 — DISMISSED** [review]
Colors are a better improvement than the previous codes color.

**Review by kimly143 — COMMENTED** [review]
Colors changes, make take cursive. commented out tests. If it good to go for other team members, i think it's good.

**Review by JeffreyAsuncion — DISMISSED** [review]
Approved and ready for merge

**Review by vetorobert3 — APPROVED** [review]
Nice job on passing the checks! Looks great to me.

**Review by kimly143 — APPROVED** [review]

**Pull request merged**
