### PR TITLE
FE weather data

### PR DESCRIPTION
**Pull request by kimly143**
------------------
https://trello.com/c/G7fYnjkk/7-as-a-user-i-would-like-to-see-more-detailed-city-data-like-weather-housing-and-traffic

-------------------------
### Location:
- CitySearchResultsContainer.js
- RenderCitySearchResults.js
- .. /actions/cityData.js
- ../reducers/cityData.js
- ### Details:
1) Fetch data from new Data from data science, including weather, renting, bikability, livability, crime, ...
-------------------------
## Committed Features:
1 | Update new Data for all field of city search
2 | Fetching current temperature at city searched.
3 | Displaying current temperature at city searched.

### CODE REVIEW

**Review by Catherinesjkim — DISMISSED** [review]
It looks good to me!

**Review by vetorobert3 — DISMISSED** [review]
Looks good to me, too.

**Review by JeffreyAsuncion — APPROVED** [review]
Way to Go. Keep up the great work!

**Review by vetorobert3 — APPROVED** [review]
Looks good. Glad you passed all the tests!

**Pull request merged**
