### PR TITLE
finished onClick handler.

### PR DESCRIPTION
**Pull request by kimly143**
Update url and verified the data is fetch correctly and fixed a small bug in query handler.

### CODE REVIEW

**Review by vetorobert3 — COMMENTED** [review]
Look at the code. Noticed correction in query handler and the correct url is verified. If it fetching correctly, then it looks good to me.

**Review by danielterry2121 — DISMISSED** [review]

**Review by Catherinesjkim — DISMISSED** [review]

**Review by samir-hub — DISMISSED** [review]
Please make sure you use the PR template that is pinned to the channel. 
PR is focused and small. Good job!

**Review by samir-hub — DISMISSED** [review]

**Review by samir-hub — DISMISSED** [review]

**Review by vetorobert3 — DISMISSED** [review]

**Comment by vetorobert3** [comment]
Failed mapbox test. Test will pass once mapbox is working.

**Review by vetorobert3 — APPROVED** [review]

**Review by samir-hub — APPROVED** [review]
Pull request is focused on one feature and the changes are easy to follow. This is helpful for us as reviewers and it will also make your life easier when trying to present this during an interview. Great job!

**Pull request merged**
