### PR TITLE
Features/veto ramirez

### PR DESCRIPTION
**Pull request by vetorobert3**
Added a css stylesheet to edit the mapbox, but still working on that. Also added 2 components for the RenderCitySearchResults.js component. Created the busability and bikeability components and change the icons for them.

### CODE REVIEW

**Review by kimly143 — DISMISSED** [review]
I don't know if Mapbox token is public or not, if it is public you can include it, normally it's a good practice to not include token in public file. Other than that, looks good.

**Review by Catherinesjkim — COMMENTED** [review]
1. It's good practice to create a new file called '.env' and add the actual Mapbox token there since .gitignore will take care of not publishing the token to the public on Github.  

2. It's also good practice to create a feature branch name that matches with what you are currently working on i.e. 'Features/RenderCitySearchResults.'

3. Create a new feature branch name called 'Features/livability' and create a separate PR for busability and bikeability components.

**Review by JeffreyAsuncion — DISMISSED** [review]
Clean code and Easy to follow.
Keep up the great work.

**Review by JeffreyAsuncion — DISMISSED** [review]
Clean code and Easy to follow.
Keep up the great work.

**Comment by tinomen** [comment]
In the future make sure never to use our names as branch names

**Review by Catherinesjkim — DISMISSED** [review]
It looks good. Please debug all test errors before merging to the main branch. Thanks!

**Review by kimly143 — DISMISSED** [review]

**Review by JeffreyAsuncion — APPROVED** [review]
Awesome, Keep that momentum going.

**Review by Catherinesjkim — APPROVED** [review]
It looks good.

**Comment by JeffreyAsuncion** [comment]
Keep up the great work.

**Pull request merged**
